### ISSUE TITLE
Autoalt doesn't use asset's title

### ISSUE THREAD

**Issue by cecilehabran** [mmikkel/Retcon-Craft#17]
> The `autoAlt` method now uses the Asset's title attribute for the alt attribute, if Retcon is fed HTML with Craft CMS reference tags.

The `autoAlt` always renders the asset's filename (which is not really useful for the SEO). How do you feed Retcon with reference tag tho? I tried the `craft.retcon.autoAlt()` method and it's the same.

Craft and Retcon are up-to-date.

**Comment by mmikkel** [comment]
Hi @cecilehabran –

Reference tags (i.e. stuff like `<img src="{asset:343:url}"/>`) are usually found in the output from Redactor fields etc. (the reference tags get parsed before the Redactor content is printed to the page). So, assuming you're using Retcon on something like the output from a Redactor field, there isn't anything you need to "do" to feed Retcon reference tags.

This isn't working as intended ATM though, due to a bug in Retcon. I plan to get this fixed shortly and will update this issue when I do.

Also – and this is also not working ATM, due to the same bug – there's actually an undocumented parameter `field` available to the `autoAlt` filter, which (when it starts working again) will let you control which field Retcon should use for the `alt` tag. So if your alternative text is in a field `alternativeText`, you'd do

```
{{ entry.body | retconAutoAlt('img', 'alternativeText') }}
```

PSA: I actually plan to give Retcon (and the docs!) a big overhaul in the coming months, and this is one of the filters that is probably going to see breaking changes. But, stay tuned for some bug fixes before that happens :)

**Comment by mmikkel** [comment]
Fixed in Retcon 2.1.0.
