### ISSUE TITLE
How do i transform img to picture tag?

### ISSUE THREAD

**Issue by faradaytrs** [mmikkel/Retcon-Craft#19]
I can't figure it out
How do i make this: `<img> `
Become this `<picture>sources here</picture>`
Just inserting sizes tags won't work because i need difference sources for webp and jpeg

srcset and sizes are great and i'm glad there is support for that, but unfortunatelly that's not enough to make webp work

**Comment by faradaytrs** [comment]
I can submit pull request but i would like to know what syntax is better for this? 
Basically it's the same with srcset function but it needs to split all sources by types and wrap with picture.

**Comment by mmikkel** [comment]
Hi @faradaytrs, sorry for the very late reply. Honestly, this is a bit beyond the scope for where I want to take this plugin – I already kinda regret adding the other transform-related filters (just because they're quite complex both to maintain and use) and I don't want to add an additional, even more complex filter to support the `picture` tag.
