### ISSUE TITLE
Add support for native lazy loading

### ISSUE THREAD

**Issue by niallthompson** [mmikkel/Retcon-Craft#26]
It's our preference to use native lazy loading for images as outlined [here](loading=lazy).

Ideally this plugin could be updated to support that.

**Comment by mmikkel** [comment]
The link you provided doesn't work, but assuming you're talking about the native `loading` attribute, you can just use the [`retconAttr`](https://github.com/mmikkel/Retcon-Craft/wiki/Attr) filter instead of `retconLazy`, like this:

```twig
{{ entry.body|retconAttr('img', { loading: 'lazy' }) }}
```

...which would add a `loading="lazy"` to all `<img>` tags in `entry.body`.

**Comment by niallthompson** [comment]
Apologies. Here's the correct link: https://web.dev/native-lazy-loading/

To work I believe it requires no quotations.

**Comment by niallthompson** [comment]
Actually according to the spec it works just fine with the quotations.

Thanks for the great plugin.

**Comment by mmikkel** [comment]
Yep, quotes are optional in HTML5 (unless you have a value w/ whitespace) – thanks for the follow-up; cool that it works :)
