### ISSUE TITLE
extract first image and transform it

### ISSUE THREAD

**Issue by pioneerdesign** [mmikkel/Retcon-Craft#46]
I'm trying to show just the first image in a text field and then transform it. 

Chaining these 2 don't seem to work:
  {{ entry.body | retconOnly('img') | retconTransform( { width : 470, height : 350 } ) }}

Is there a way to identify just the first image as well and ignore the rest?

**Comment by mmikkel** [comment]
Not really, but you could probably hack it by doing something like

```twig
{{ entry.body | retconOnly('img') | retconOnly('img:first-child') | retconTransform( { width : 470, height : 350 } ) }}
```

I.e. first use `retconOnly('img')` to make sure the HTML contains only `img` nodes; then use `retconOnly('img:first-child')` to strip out all those images except the first one (and finally, transform that).

**Comment by pioneerdesign** [comment]
It appears this combination doesn't return anything:
{{ entry.body | retconOnly('img') | retconTransform( { width : 470, height : 350 } ) }}

but {{ entry.body | retconOnly('img')  }} works
Is there some other way to combine selecting an image and then transforming it?

**Comment by mmikkel** [comment]
That should work, i.e. `{{ entry.body | retconOnly('img') | retconTransform( { width : 470, height : 350 } ) }}` should render all the `img` tags (and only the `img` tags) in the HTML, transformed, whereas `{{ entry.body | retconOnly('img') | retconOnly('img:first-child') | retconTransform( { width : 470, height : 350 } ) }}` should render only the first `img`, also transformed. Are you saying your getting empty output?

What does the below print, on your end?

```twig
{% dd entry.body | retconOnly('img') %}
```

**Comment by mmikkel** [comment]
Aha. So everything is actually working as expected, you're just running into an unfortunate gotcha:

When Imager is passed a _string_ (i.e. a URL or path) instead of an asset (which is necessarily the case when transforming images using Retcon), it will have no clue about the actual asset. When using the Imgix transformer, essentially this means that the string is simply appended as-is to your Imigix domain.

Since your image tags' `src` include full URLs, essentially this means that Imgix interprets the resulting transform URLs as [web proxy](https://docs.imgix.com/setup/serving-assets#web-proxy) URLs. Assuming your Imgix source isn't actually a web proxy, this is why they fail.

To work around the issue, there's a few options I can think of:

1. Set up a new Imgix web proxy source for these transforms, add a profile for it to your Imager config file, and override the default profile like this:

```twig
{{ entry.body | retconOnly('img') | retconOnly('img:first-child') | retconTransform( { width : 470, height : 350 }, null, { imgixProfile: 'someProxySource' ) }}
```

2. Use native Craft transforms instead of Imgix for these transforms, by overriding Imager's `transformer` setting:

```twig
{{ entry.body | retconOnly('img') | retconOnly('img:first-child') | retconTransform( { width : 470, height : 350 }, null, { transformer: 'craft' ) }}
```

3. Remove the hostname from your filesystem's Base URL setting (i.e. set it to `/`)

4. Strip the hostname from the HTML before doing the transform, i.e. something like 

```twig
{{ entry.body | retconOnly('img') | retconOnly('img:first-child') | replace(siteUrl(), '') | retconTransform( { width : 470, height : 350 }) }}
```

**Comment by pioneerdesign** [comment]
Thanks so much! I fixed the source urls and all was golden.
