### ISSUE TITLE
Default img for src when using srcsetq

### ISSUE THREAD

**Issue by codecreate** [mmikkel/Retcon-Craft#5]
Hi,

Is there any parameter or way to determine the default image for the img tag when using |retconSrcset?

Ideally I want to select a transform for the default image, not the original?

Thanks
Andy

**Comment by codecreate** [comment]
Hi,

Any feedback on this?


Andy

**Comment by mmikkel** [comment]
Hi @codecreate, sorry for the delayed reply.

I'm not quite sure I understand what you're looking for here. Could you please elaborate/be more specific (possibly describe a use case)?

**Comment by codecreate** [comment]
Hi,

Here's a srcset block created by retcon on a production site. It all looks good and works fine but the src attribute is the original image that was uploaded. It's a larger image than we ever want to include on the site and we're working hard to optimise the website for performance. What I want to do is make the src attribute load up a smaller transformed version of the image.


<img alt="Heart Foundation Walking website showing skip to navigation" title="Heart Foundation Walking website showing skip to navigation" sizes="100w" data-src="https://uat.lemonade.com.au/uploads/HFW_18.jpg" data-srcset="https://uat.lemonade.com.au/uploads/_inlineSmall/HFW_18.jpg 414w, https://uat.lemonade.com.au/uploads/_inlineLarge/HFW_18.jpg 1720w" src="https://uat.lemonade.com.au/uploads/HFW_18.jpg">

**Comment by mmikkel** [comment]
The easiest option would be to use `retconTransform` as a second filter after `retconSrcset`:

```twig
{{ entry.body | retconSrcset([...transforms]) | retconTransform({ width: 720 }) }}
```

However, I notice that your `img` tag is actually missing its `src` attribute – it's called `data-src` instead – so the above won't work (`retconTransform` will only look at the `src` attribute).

If you can, I'd rename the `data-src` attribute to `src`, use `retconTransform` as in the example above, and then use the `retconRenameAttr` filter to change the `src` to `data-src`:

```twig
{{ entry.body | retconSrcset([...transforms]) | retconTransform({ width: 720 }) | retconRenameAttr('img', { src: 'data-src' }) }}
```

Depending on your needs you can make the `retconRenameAttr` filter target only the images that have the `srcset` or `data-srcset` attribute:

```twig
{{ entry.body ... | retconRenameAttr('img[data-srcset]', { src: 'data-src' }) }}
```

Finally, be aware that the `retconSrcset` filter can also drop in a tiny, base64-encoded, SVG as a placeholder `src` attribute (with the correct aspect ratio), by passing `true` as the fourth parameter:

```twig
{{ entry.body | retconSrcset([...transforms], 'img', '100vw', true) }}
```

This above is the method I typically use; I use [lazysizes.js](https://github.com/aFarkas/lazysizes) to load the images and having a `src` attribute with a tiny footprint but with the proper aspect ratio is good to avoid both FOUC and redundant bandwidth usage.

The only reason to actually have an actual image in the `src` attribute is to support browsers that don't support the `srcset` attribute; since you're actually using `src` and `data-src` I suspect you're (like me) using a JS lib to load the images in and it doesn't actually even need to be there :)

Hope the above was helpful. Thanks for checking out Retcon!

**Comment by codecreate** [comment]
Thanks
