### ISSUE TITLE
Wiki is misleading

### ISSUE THREAD

**Issue by webrgp** [mmikkel/Retcon-Craft#50]
Great plugin!

I've tried to use the [replace](https://github.com/mmikkel/Retcon-Craft/wiki/Replace) filter that is mentioned in the Wiki and it didn't work. After a bit more digging, it seems it isn't implemented.

Maybe you should hide the Wiki page?

**Comment by mmikkel** [comment]
Hi @webrgp, thanks for reporting that. The `retconReplace` filter was removed in Retcon 2.0 back in 2018, so that wiki page should've been long gone. Deleted it now.

You should be able achieve the same thing using the core [`replace`](https://craftcms.com/docs/4.x/dev/filters.html#replace) filter btw :)

**Comment by webrgp** [comment]
Really? I didn't think I could pass regex to it?

**Comment by mmikkel** [comment]
@webrgp You can, check out the link to the offical docs in my comment above :)
