### ISSUE TITLE
Can't seem to get retcon img transforms working with Imager/Servd

### ISSUE THREAD

**Issue by alexr8** [mmikkel/Retcon-Craft#62]
I'm not sure if this is a potential issue on the Retcon side or Imager or if I'm missing something else. Following the examples for adding srcset to images, I can't seem to be able to get Retcon to apply any transforms to images in my rich text field.
```
{{ entry.body|retconSrcset(
    [
        {width: 375},
        {width: 480},
        {width: 768}
    ],
    'img',
    '(min-width: 40em) 80vw, 100vw'
) }}
```
I use the Imager-X plugin, and I'm using [Servd](https://servd.host/) as the asset transformer in my imager-x config file (Servd has its own image CDN and transform service as part of its hosting):
```
return [

	'*' => [
		'transformer' => 'servd',
	]
];
```
Even just using a basic transform doesn't seem to affect the image either.
```
{{ entry.body | retconTransform( { width : 1024, height : 768, mode : 'fit' } ) }}
```
I figured i might be running into something along these lines, despite me using Imager-X, but not sure how i can approach debugging this?
```
If you don't use Imager, please note that Retcon will not transform external images (Imager will, though!).
```
I should note that imager-x transforms images fine in my templates outside of retcon.

Any help would be useful, and thanks for your work on the plugin, it's been very useful across many projects!

**Comment by mmikkel** [comment]
I've never used Servd, but also assumed that their Imager transformer would work out of the box (see https://github.com/mmikkel/Retcon-Craft/issues/60#issuecomment-1638307400). It clearly doesn't, though – and after doing a bit of digging I figured out why:

Retcon attempts to transform assets by their URL (i.e. a string; the URL referenced by the `img` nodes' `src` attribute). 

For the stock `craft` transformer in Imager, this isn't a problem, but [the Servd transformer only accepts URLs using the `.assets-servd.host` domain](https://github.com/servdhost/craft-asset-storage/blob/c32ad0a2bad7862a5ff4e3edd4897eb777eccb43/src/Imager/ImagerTransformer.php#L45). I have minimal experience with Servd, but I believe images output by Redactor and CKEditor fields in most cases will either be served by a `.transforms.svdcdn.com` domain, or even a custom domain, if that has been set up in the Servd CP. Hence, the Servd transformer refuses to transform the image.

A potential solve in Retcon would be if `retconSrcset` (and `retconTransform`) started looking at [reference tags](https://craftcms.com/docs/4.x/reference-tags.html) in Redactor/CKEditor output, in order to _transform the actual assets instead of their URLs_. I've actually been [planning to make that change](https://github.com/mmikkel/Retcon-Craft/commit/9dc8e8eabd7aa53e2db067cc3e563bd31ebe3532), but probably not outside of a major release (i.e. Retcon 3.0) as it has the potential to impact existing installs badly.

**Comment by alexr8** [comment]
I spoke with Servd support and they've updated and released a new version of their plugin which fixes the issue. https://github.com/servdhost/craft-asset-storage/releases/tag/v3.4.8

I've not extensively tested it but so far seems to all be working as expected. Thanks for your swift reply @mmikkel.

**Comment by mmikkel** [comment]
Oh, that’s awesome! Thanks a lot for the follow up @alexr8!
