### ISSUE TITLE
Retcon breaking entry and asset links in Redactor

### ISSUE THREAD

**Issue by mattias78** [mmikkel/Retcon-Craft#63]
Hey, I've noticed when I use Retcon on my Redactor fields it breaks entry and asset links.

I get 404's from weird urls generated that look like:

`https://example.com/%7Bentry:8350@1:url||https://example.com/privacy-policy%7D`

If I view source on the Redactor field in the CP the link is:
`https://example.com/privacy-policy#entry:8350@1`

My template twig with basic redactor field for testing:
`{{ entry.testRedactor | retconAttr('img', { class: 'custom-image' }) }}`

Any idea what's happening here?

Craft Pro 4.4.16.1
Redactor 3.0.4
Retcon 2.7.2

**Comment by mmikkel** [comment]
Ouch, that looks like a regression introduced in Recton v. 2.7.0. It only happens when there are no nodes matching the query (in this case, `img`) in the Redactor/CKEditor output.

I'll get a fix out ASAP, in the interim you can either

* Downgrade Retcon to v. 2.6.1

* Append the `|parseRefs` filter to the output, i.e.

```twig
{{ entry.testRedactor | retconAttr('img', { class: 'custom-image' }) | parseRefs }}
```

**Comment by mattias78** [comment]
Thanks for the prompt reply :)

**Comment by mmikkel** [comment]
@mattias78 Should be all fixed in Retcon v. 2.7.3.

Thanks for the report!
