### ISSUE TITLE
[4.x] retconAutoAlt doesn't use asset's title

### ISSUE THREAD

**Issue by anita-chouhan** [mmikkel/Retcon-Craft#71]
The `retconAutoAlt` renders the asset's filename in place of the title (as mentioned in the [doc](https://github.com/mmikkel/Retcon-Craft/wiki/AutoAlt)). 

**Expected**
`{{ html |retconAutoAlt }}`
Asset title as `alt` tag value if no alt value is supplied by the author for the rich content field image.

**Outcome**
`{{ html |retconAutoAlt }}`
Asset filename as `alt` tag value if no alt value is supplied.

**Plugin version**
2.8.0

**Craft CMS version**
4.9.7

**Comment by mmikkel** [comment]
I'm not able to reproduce that.

Where does the `html` variable come from and what does it contain? If you do a `{{ dump(html) }}` in your template, what does the output look like (a screen dump is fine, if you can share)?

**Comment by anita-chouhan** [comment]
The variable contains the rich text content from CKEditor. Here is the output of `{{ dump(html) }}` and `{{ dump(html|retconAutoAlt) }}`.

<img width="682" alt="Screenshot 2024-10-14 at 10 33 19 AM" src="https://github.com/user-attachments/assets/3d758e3a-c2b2-47db-bc75-da7aa2bb0d60">

<img width="692" alt="Screenshot 2024-10-14 at 10 25 26 AM" src="https://github.com/user-attachments/assets/a616e3dd-d235-4af7-8c7d-7a060bc28433">

The asset title is _Colorful bird_ and file name is _bird-thumbnail.jpeg_. I was expecting the alt to show Colorful bird and not bird-thumbnail.

<img width="1026" alt="Screenshot 2024-10-14 at 10 27 00 AM" src="https://github.com/user-attachments/assets/ca86f308-2d7c-416e-8c09-70628389b313">

**Comment by mmikkel** [comment]
Thanks for the extra info!

The reason why `retconAutoAlt` isn’t able to output the asset’s title is because your CKEditor field’s output has already been rendered to a string (or rather, a `Twig\Markup` object) - hence the [reference tags](https://craftcms.com/docs/5.x/system/reference-tags.html) found in raw CKEditor output have been lost. For the autoAlt feature, Retcon relies on those tags for querying for the original asset, falling back to using the file name if it can’t be found.

Most likely, this occurs because the CKEditor output has been passed through another Twig filter (or some other operation that renders its raw content down to a Twig markup object), before the `retconAutoAlt` operation.

To ensure that the `retconAutoAlt` filter works as intended, make sure that this filter is the first operation on the CKEditor output.

**Comment by anita-chouhan** [comment]
Okay, thank you for looking into it. I'll check for the other filters.

**Comment by itsmattsoria** [comment]
I can recreate this same behavior. I've ensured that the very first filter applied is `retconAutoAlt`, and even tested turning `Purify HTML` off for the filter, and still no matter how I set the three options, or if I just leave them as default, I'm getting the filename output as the alt text value. I'm on Craft 5.4.7.1 and Retcon 3.2.0. I also had some other Retcon filters I was applying and I tested removing all of them and still got the same result.

**Comment by itsmattsoria** [comment]
@mmikkel I'm sorry, I'm using CKEditor 4.2.0. Here's my twig code:
```
{{ entry.longFormContent|retconAutoAlt(null, false, false) }}
```
Where `longFormContent` is a CKEditor field.

**Comment by itsmattsoria** [comment]
@mmikkel Amazing—thank you!

**Comment by mmikkel** [comment]
This turned out to be a regression introduced in https://github.com/mmikkel/Retcon-Craft/commit/17a58efd73c248e9b7304771c7a9b95d339466ee. I'll get a release out w/ the fix as soon as possible, but there are a couple of other things I'm hoping to get to. If you need it straight it away, change your Composer dependency for Retcon in `composer.json` to  

```
"mmikkel/retcon": "dev-master#dcd459ac22f9fa54b9b149e9057d4ec83c98c6c0 as 3.2.0"
```

...then run `composer update`.

**Comment by itsmattsoria** [comment]
@mmikkel awesome, thanks!

**Comment by mmikkel** [comment]
@itsmattsoria [Retcon v. 3.2.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/3.2.1) is out now with that fix.

**Comment by itsmattsoria** [comment]
@mmikkel amazing, thank you!
